# Generated by Django 4.0.5 on 2022-12-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='backlogs',
            field=models.IntegerField(default=0, verbose_name='Backlogs'),
        ),
    ]
