# Generated by Django 4.0.5 on 2022-12-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_backlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='student',
            name='allocated',
            field=models.BooleanField(default=True, verbose_name='Allocated'),
        ),
        migrations.AddField(
            model_name='student',
            name='application_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Jee Mains Application No'),
        ),
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='DOB'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_prep',
            field=models.BooleanField(default=False, verbose_name='Is Prep'),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Mobile'),
        ),
        migrations.AddField(
            model_name='student',
            name='mothers_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mothers Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='student',
            name='pwd',
            field=models.BooleanField(default=False, verbose_name='PwD'),
        ),
        migrations.AddField(
            model_name='student',
            name='soe',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State of Eligibility'),
        ),
    ]
