# Generated by Django 4.0.5 on 2022-12-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_address_student_allocated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='application_no',
            new_name='jee_application_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='allocated',
        ),
        migrations.AddField(
            model_name='student',
            name='allocated_cat',
            field=models.BooleanField(default=True, verbose_name='Allocated Category'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_prep',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True, verbose_name='Is Prep'),
        ),
    ]
