# Generated by Django 4.0.5 on 2022-12-23 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_rename_application_no_student_jee_application_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='soe',
            new_name='state_of_eligibility',
        ),
    ]
