# Generated by Django 4.0.5 on 2022-12-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student_remarks_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Address'),
        ),
    ]
