# Generated by Django 4.0.5 on 2022-12-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_student_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='allocated_cat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Allocated Category'),
        ),
    ]
