# Generated by Django 4.0.5 on 2022-12-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0002_alter_semester_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterinstance',
            name='sr_no',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Sr. No.'),
        ),
    ]
