# Generated by Django 4.0.5 on 2023-02-05 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0004_alter_semesterinstance_elective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semesterinstance',
            name='sr_no',
        ),
    ]
