# Generated by Django 4.0.5 on 2023-02-14 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0005_remove_semesterinstance_sr_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semesterinstance',
            name='cg_sum',
        ),
    ]
